# Generated by Django 4.1.3 on 2022-11-24 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('body', models.TextField(max_length=250)),
                ('expiry_date', models.DateTimeField()),
                ('is_done', models.BooleanField(default=False)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(blank=True, max_length=1000)),
                ('public_id', models.CharField(blank=True, max_length=1000)),
                ('task', models.ForeignKey(help_text='Please attach files', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='todo_list.task', verbose_name='task_files')),
            ],
        ),
    ]
